### ISSUE TITLE
Data Privacy

### ISSUE THREAD

**Issue by Hakeemmidan** [locize/translation-check#2]
## 🚀 Feature Proposal
Include what data is collected (if any) by locize in the README. 

## Motivation
This will make it easier for companies to decide whether to use this package or not.

## Example
```
We collect all the inputted translation keys and store them in locize cloud to make it easier for users to later upgrade. 
```

**Comment by adrai** [comment]
nothing at all is collected from our side...
it's just a small react app statically hosted on gh-pages.
All is done on client side only.

**Comment by Hakeemmidan** [comment]
By it I assume you mean https://mini.locize.com which opens when using the plugin, is that right? 

So the data is only sent and displayed there, it doesn't get stored in the cloud or anything like that?

**Comment by adrai** [comment]
Yes, mini.locize.com is just a react app published on gh-pages

**Comment by Hakeemmidan** [comment]
Sounds good. Thank you.

I still suggest adding that info in the README so I'll leave this open, and have the maintainers close it based on their decision on whether to add that info or not.

**Comment by CyberCyclone** [comment]
@adrai Is there a open-source version of https://mini.locize.com/ that we can run locally? For privacy reasons we can't transfer any data to another server, even if you say it's a simple react app that you don't collect data from.

**Comment by adrai** [comment]
> @adrai Is there a open-source version of https://mini.locize.com/ that we can run locally? For privacy reasons we can't transfer any data to another server, even if you say it's a simple react app that you don't collect data from.

No
