### ISSUE TITLE
Misleading "Cannot read properties of null (reading 'postMessage')" error

### ISSUE THREAD

**Issue by neatbyte-vnobis** [locize/translation-check#4]
## 🐛 Bug Report

If browser page settings are defined to block popups by default user will see misleading error message:
```
ERROR
Cannot read properties of null (reading 'postMessage')
TypeError: Cannot read properties of null (reading 'postMessage')
```
In order to fix this just allow popup for a page.
![image](https://user-images.githubusercontent.com/77202393/232291400-9003ba24-6dc7-41e8-87cb-67dae6aaf207.png)

## To Reproduce

Block popup for a page and use `?showtranslations` query param in your app.

## Expected behavior

Check if `window.open` returns null and more clear error message that can suggest to take a look on browser settings for this page.

## Your Environment

- *runtime version*: browser
- *module version*: "i18next": "^22.4.14", "translation-check": "^1.0.2",
- *os*: Linux

**Comment by adrai** [comment]
Would you like to provide a PR?

**Comment by adrai** [comment]
v1.0.3
